### ISSUE TITLE
UpdateServicesServer Classification should use Title, not GUID

### ISSUE THREAD

**Issue by russellds** [dsccommunity/UpdateServicesDsc#17]
The UpdateServicesServer Classification property should use the Classification Title, not the GUID. This makes the DSC configuration file both easier to read and easier to maintain.

**Comment by rob-willis** [comment]
That would make the resource language specific to English since classification titles are localized.

**Comment by russellds** [comment]
What if Classification could take either GUIDs or Titles? Then it would work for both use cases.
