### ISSUE TITLE
Powershell DSC Repo

### ISSUE THREAD

**Issue by Zuldan** [dsccommunity/UpdateServicesDsc#19]
Just wondering if this resource is still planned to be merged into the Powershell DSC repo? https://github.com/PowerShell/DscResources

**Comment by gaelcolas** [comment]
Yes, however it's still a work in progress. See PowerShell/DscResources#346 for progress.

**Comment by gaelcolas** [comment]
Closing this issue here, feel free to follow up in the PR mentioned above.
