### ISSUE TITLE
UpdateServicesDsc - Is out of date on Powershell Gallery

### ISSUE THREAD

**Issue by jcoconnor** [dsccommunity/UpdateServicesDsc#37]
The current version of ```UpdateServicesDsc``` in the Powershell Gallery is ```1.0.75.0``` dated ```31/Mar/2018```

Is there a plan to update the gallery ?

Thanks - John

**Comment by gaelcolas** [comment]
Hey John, I'm in a position where I'm happy to publish a new version, but I'd like to confirm that there aren't breaking changes since `1.0.75.0`.
Otherwise I'll just bump the major version.

Your input would be greatly appreciated.

**Comment by jcoconnor** [comment]
@gaelcolas - If I pull down the HEAD and try it locally will that suffice ?
I'll also need to review the changes since 31-Mar-2018 which is when 1.0.75.0 was released.

**Comment by jcoconnor** [comment]
Also - which is the source of truth for Update History/Unreleased - The Changelog.md which only records up to 1.0.75.0 (i.e. what's actually published), and the Readme.md which goes right up to version 1.1.0

**Comment by jcoconnor** [comment]
@gaelcolas I've looked through all the changes and they seem to come into the following categories:
* Address PSSA issues
* Improve Robustness (e.g. handling deletion of Approval Rules)
* Readme updates

So I'm not seeing any breaking changes.

I'm hoping to get a window later in the week to fully test the latest Dev HEAD in our soon to be production environment and will let you know if I find any issues.

**Comment by gaelcolas** [comment]
I've just landed. Might publish overnight.
Thanks for confirming my thoughts.

**Comment by jcoconnor** [comment]
👍

**Comment by gaelcolas** [comment]
I just released and published version 1.1.0.0 to the Gallery.
Please test and let me know if any issue.
