### ISSUE TITLE
[UpdateServicesServer]: master branch resource mistype in if statement for #ClientTargetingMode check

### ISSUE THREAD

**Issue by phoenix2pm** [dsccommunity/UpdateServicesDsc#46]
#### Details of the scenario you tried and the problem that is occurring
UpdateServicesServer: Set-TargetResource mistype in check #ClientTargetingMode
 spaces in "Client Targeting Mode", wherefore test is failing and DSC is throwing error

```powershell
#ClientTargetingMode
        if($PSBoundParameters.ContainsKey("Client Targeting Mode"))
```
#### Suggested solution to the issue
Merge dev branch which has correct syntax to master branch. 

#### Version of the DSC module that was used ('dev' if using current dev branch)
master

**Comment by Firefishy** [comment]
This appears to be fixed on the master branch and the v1.2.0 preview release https://github.com/dsccommunity/UpdateServicesDsc/releases/tag/v1.2.0-preview0001

**Comment by Firefishy** [comment]
@johlju ^

**Comment by johlju** [comment]
Great thank you! Closing this as fixed.
