### ISSUE TITLE
UpdateServicesServer: WSUS.cab file is missing products 

### ISSUE THREAD

**Issue by Firefishy** [dsccommunity/UpdateServicesDsc#51]
#### Details of the scenario you tried and the problem that is occurring
The initial sync `WSUS.cab` file is out of date and is missing `Windows Server 2019` and other products.

The following snippet fails because `Windows Server 2019` is not a known product.
```
UpdateServicesServer 'UpdateServices' {
  Synchronize = $false # Default, use WSUS.cab
  Products = @(
    'Windows Server 2019'
  )
 ...
```

#### Verbose logs showing the problem
```
[[UpdateServicesServer]UpdateServices] Products test failed
[[UpdateServicesServer]UpdateServices] Test-TargetResouce returned false after calling set. | ErrorType: MSFT_UpdateServicesServer.TestFailedAfterSet
```

After a full sync, `Windows Server 2019` product can be used.

#### Suggested solution to the issue
Please update bundled WSUS metadata export in `WSUS.cab`

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
See above.
```

#### The operating system the target node is running
Windows Server 2019

#### Version and build of PowerShell the target node is running
5.1.17763.1007

#### Version of the DSC module that was used
UpdateServicesDsc 1.1.0.0

**Comment by Firefishy** [comment]
A full manual sync fixed the issue, but it would be good to be able to enable the product without having 2x DSC runs.

**Comment by Firefishy** [comment]
Specifically it is this file which is out of date: https://github.com/dsccommunity/UpdateServicesDsc/blob/master/source/DSCResources/MSFT_UpdateServicesServer/WSUS.cab

**Comment by Firefishy** [comment]
Would it help if I documented the procedure to create an updated version of `WSUS.cab`?

**Comment by gaelcolas** [comment]
Yes please, documenting that step would be very helpful :)
